home:
  dir: 'C:/Users/liuxiaoming'
#  dir: '~/liuxiaoming'

# Please set the GPU or CPU to be used for your model training in the LoadConfig object
device: ~

# shared for multiple projects in this machine, raw data, read only
data:
  # base: '/datasets'
  base: 'd:/ZUTNLP/data'
  ctb:
    dir: '{data.base}/ctb/ctb8/ner'
    train: '{data.ctb.dir}/ner_train.txt'
    valid: '{data.ctb.dir}/ner_valid.txt'
    test: '{data.ctb.dir}/ner_test.txt'
  msra:
    dir: '{data.base}/msra'
    train: '{data.msra.dir}/train'
    valid: '{data.msra.dir}/valid'
    test: '{data.msra.dir}/test'
  conll2003:
    dir:  '{data.base}/conll/CoNLL-2003'
    train: '{data.conll2003.dir}/eng.train'
    valid: '{data.conll2003.dir}/eng.valid'
    test: '{data.conll2003.dir}/eng.test'

# Shared for multiple modules in the project
project:
  name: 'transfer_learning'
  dir:
    work: "{home.dir}/workspace/{project.name}"


# specified for specific module
module:
  name: 'cross_domain_ner'

  dir:
    work: "{project.dir.work}/{module.name}"
    data: "{module.dir.work}/data"
    log:  '{module.dir.work}/log'
    summary: '{module.dir.work}/summary'
    saved: '{module.dir.work}/saved'
    result: '{module.dir.work}/result'

  train:
    batch_size: 128
    epoch: 100
    lr: 1.0e-4
    dropout: 0.5

  valid:
    epoch: 100

  test:
    batch_size: 128
    epoch: 100

model:
  bilstm_crf:
    embedding_dim: 300
    hidden_dim: 300
    num_layers: 2
    dropout: 0.5
